# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'show_track.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def __init__(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.camera_button = QtWidgets.QPushButton(self.centralwidget)
        self.camera_button.setGeometry(QtCore.QRect(240, 510, 121, 51))
        self.camera_button.setObjectName("camera_button")
        self.camera_label = QtWidgets.QLabel(self.centralwidget)
        self.camera_label.setGeometry(QtCore.QRect(100, 10, 640, 480))
        self.camera_label.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.camera_label.setText("")
        self.camera_label.setObjectName("camera_label")
        self.show_track_button = QtWidgets.QPushButton(self.centralwidget)
        self.show_track_button.setGeometry(QtCore.QRect(450, 510, 121, 51))
        self.show_track_button.setObjectName("show_track_button")
        self.track_label = QtWidgets.QLabel(self.centralwidget)
        self.track_label.setGeometry(QtCore.QRect(100, 10, 640, 480))
        self.track_label.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.track_label.setText("")
        self.track_label.setObjectName("track_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.camera_button.setText(_translate("MainWindow", "Open Camera"))
        self.show_track_button.setText(_translate("MainWindow", "Show Track"))
